using System;
using System.Collections.Generic;
using System.Linq;
using MosuPp.Util;

namespace MosuPp.Osu
{
    /// <summary>Port of rosu-pp's <c>StrainSkill</c> (generated by the <c>define_skill!</c> macro).</summary>
    internal abstract class StrainSkill
    {
        protected const double DecayWeight = 0.9;
        protected const int SectionLength = 400;

        private double currentSectionPeak;
        private double currentSectionEnd;
        private readonly List<double> strainPeaks = new List<double>(256);
        protected readonly List<double> ObjectStrainsList = new List<double>(256);

        public IReadOnlyList<double> ObjectStrains => ObjectStrainsList;

        protected abstract double CalculateInitialStrain(double time, OsuDifficultyObject curr, List<OsuDifficultyObject> objects);

        protected abstract double StrainValueAt(OsuDifficultyObject curr, List<OsuDifficultyObject> objects);

        protected abstract double DifficultyValue(List<double> currentStrainPeaks);

        public void Process(OsuDifficultyObject curr, List<OsuDifficultyObject> objects)
        {
            const double sectionLength = SectionLength;

            // * The first object doesn't generate a strain, so we begin with an incremented section end
            if (curr.Idx == 0)
                currentSectionEnd = Math.Ceiling(curr.StartTime / sectionLength) * sectionLength;

            while (curr.StartTime > currentSectionEnd)
            {
                SaveCurrentPeak();
                StartNewSectionFrom(currentSectionEnd, curr, objects);
                currentSectionEnd += sectionLength;
            }

            double strain = StrainValueAt(curr, objects);
            currentSectionPeak = RustMath.Max(strain, currentSectionPeak);

            // * Store the strain value for the object
            ObjectStrainsList.Add(strain);
        }

        private void SaveCurrentPeak() => strainPeaks.Add(currentSectionPeak);

        private void StartNewSectionFrom(double time, OsuDifficultyObject curr, List<OsuDifficultyObject> objects)
            => currentSectionPeak = CalculateInitialStrain(time, curr, objects);

        public List<double> GetCurrentStrainPeaks()
        {
            var peaks = new List<double>(strainPeaks) { currentSectionPeak };
            return peaks;
        }

        public double CountTopWeightedStrains(double difficultyValue)
        {
            if (ObjectStrainsList.Count == 0)
                return 0.0;

            // * What would the top strain be if all strain values were identical
            double consistentTopStrain = difficultyValue / 10.0;

            if (RustMath.AlmostEq(consistentTopStrain, 0.0))
                return ObjectStrainsList.Count;

            // * Use a weighted sum of all strains. Constants are arbitrary and give nice values
            double sum = 0.0;

            foreach (double s in ObjectStrainsList)
                sum += 1.1 / (1.0 + Math.Exp(-10.0 * (s / consistentTopStrain - 0.88)));

            return sum;
        }

        public double GetDifficultyValue() => DifficultyValue(GetCurrentStrainPeaks());

        protected static double StrainDecay(double ms, double strainDecayBase) => Math.Pow(strainDecayBase, ms / 1000.0);

        /// <summary>Sorts descending with the total order (C#'s OrderByDescending is stable; ties are equal values anyway).</summary>
        protected static List<double> OrderDescending(List<double> values)
        {
            var sorted = new List<double>(values);
            sorted.Sort((a, b) => RustMath.TotalCmp(b, a));
            return sorted;
        }
    }

    /// <summary>Port of rosu-pp's <c>OsuStrainSkill</c> helpers.</summary>
    internal static class OsuStrainSkill
    {
        public const int ReducedSectionCount = 10;
        public const double ReducedStrainBaseline = 0.75;

        public static double DifficultyValue(List<double> currentStrainPeaks, int reducedSectionCount, double reducedStrainBaseline, double decayWeight)
        {
            double difficulty = 0.0;
            double weight = 1.0;

            // * Sections with 0 strain are excluded to avoid worst-case time complexity of the following sort (e.g. /b/2351871).
            // * These sections will not contribute to the difficulty.
            var peaks = currentStrainPeaks.Where(p => p > 0.0).ToList();

            peaks.Sort((a, b) => RustMath.TotalCmp(b, a));

            for (int i = 0; i < Math.Min(reducedSectionCount, peaks.Count); i++)
            {
                double clamped = RustMath.Clamp((float)i / (float)reducedSectionCount, 0f, 1f);
                double scale = Math.Log10(Lerp(1.0, 10.0, clamped));
                peaks[i] *= Lerp(reducedStrainBaseline, 1.0, scale);
            }

            peaks.Sort((a, b) => RustMath.TotalCmp(b, a));

            foreach (double strain in peaks)
            {
                difficulty += strain * weight;
                weight *= decayWeight;
            }

            return difficulty;
        }

        public static double CountTopWeightedSliders(IReadOnlyList<double> sliderStrains, double difficultyValue)
        {
            if (sliderStrains.Count == 0)
                return 0.0;

            // * What would the top strain be if all strain values were identical
            double consistentTopStrain = difficultyValue / 10.0;

            if (RustMath.AlmostEq(consistentTopStrain, 0.0))
                return 0.0;

            double sum = 0.0;

            foreach (double s in sliderStrains)
                sum += DifficultyUtil.Logistic(s / consistentTopStrain, 0.88, 10.0, 1.1);

            return sum;
        }

        public static double DifficultyToPerformance(double difficulty) => Math.Pow(5.0 * RustMath.Max(1.0, difficulty / 0.0675) - 4.0, 3.0) / 100_000.0;

        private static double Lerp(double start, double end, double amount) => start + (end - start) * amount;
    }

    internal sealed class AimSkill : StrainSkill
    {
        private const double SkillMultiplier = 26.0;
        private const double StrainDecayBase = 0.15;

        private readonly bool includeSliders;
        private double currentStrain;
        private readonly List<double> sliderStrains = new List<double>(64);

        public AimSkill(bool includeSliders)
        {
            this.includeSliders = includeSliders;
        }

        public IReadOnlyList<double> SliderStrains => sliderStrains;

        protected override double CalculateInitialStrain(double time, OsuDifficultyObject curr, List<OsuDifficultyObject> objects)
        {
            double prevStartTime = curr.Previous(0, objects)?.StartTime ?? 0.0;

            return currentStrain * StrainDecay(time - prevStartTime, StrainDecayBase);
        }

        protected override double StrainValueAt(OsuDifficultyObject curr, List<OsuDifficultyObject> objects)
        {
            currentStrain *= StrainDecay(curr.DeltaTime, StrainDecayBase);
            currentStrain += AimEvaluator.EvaluateDiffOf(curr, objects, includeSliders) * SkillMultiplier;

            if (curr.Base.IsSlider)
                sliderStrains.Add(currentStrain);

            return currentStrain;
        }

        public double GetDifficultSliders()
        {
            if (sliderStrains.Count == 0)
                return 0.0;

            double maxSliderStrain = 0.0;

            foreach (double s in sliderStrains)
                maxSliderStrain = RustMath.Max(maxSliderStrain, s);

            if (RustMath.AlmostEq(maxSliderStrain, 0.0))
                return 0.0;

            double sum = 0.0;

            foreach (double strain in sliderStrains)
                sum += 1.0 / (1.0 + Math.Exp(-(strain / maxSliderStrain * 12.0 - 6.0)));

            return sum;
        }

        protected override double DifficultyValue(List<double> currentStrainPeaks)
            => OsuStrainSkill.DifficultyValue(currentStrainPeaks, OsuStrainSkill.ReducedSectionCount, OsuStrainSkill.ReducedStrainBaseline, DecayWeight);

        public static double DifficultyToPerformance(double difficulty) => OsuStrainSkill.DifficultyToPerformance(difficulty);
    }

    internal sealed class SpeedSkill : StrainSkill
    {
        private const double SkillMultiplier = 1.47;
        private const double StrainDecayBase = 0.3;
        private const int SpeedReducedSectionCount = 5;

        private double currentStrain;
        private double currentRhythm;
        private readonly double hitWindow;
        private readonly bool hasAutopilotMod;
        private readonly List<double> sliderStrains = new List<double>(64);

        public SpeedSkill(double hitWindow, bool hasAutopilotMod)
        {
            this.hitWindow = hitWindow;
            this.hasAutopilotMod = hasAutopilotMod;
        }

        public IReadOnlyList<double> SliderStrains => sliderStrains;

        protected override double CalculateInitialStrain(double time, OsuDifficultyObject curr, List<OsuDifficultyObject> objects)
        {
            double prevStartTime = curr.Previous(0, objects)?.StartTime ?? 0.0;

            return (currentStrain * currentRhythm) * StrainDecay(time - prevStartTime, StrainDecayBase);
        }

        protected override double StrainValueAt(OsuDifficultyObject curr, List<OsuDifficultyObject> objects)
        {
            currentStrain *= StrainDecay(curr.AdjustedDeltaTime, StrainDecayBase);
            currentStrain += SpeedEvaluator.EvaluateDiffOf(curr, objects, hitWindow, hasAutopilotMod) * SkillMultiplier;
            currentRhythm = RhythmEvaluator.EvaluateDiffOf(curr, objects, hitWindow);

            double totalStrain = currentStrain * currentRhythm;

            if (curr.Base.IsSlider)
                sliderStrains.Add(totalStrain);

            return totalStrain;
        }

        public double RelevantNoteCount()
        {
            if (ObjectStrainsList.Count == 0)
                return 0.0;

            double maxStrain = ObjectStrainsList[0];

            foreach (double s in ObjectStrainsList)
            {
                if (RustMath.TotalCmp(s, maxStrain) >= 0)
                    maxStrain = s;
            }

            if (!(maxStrain > 0.0))
                return 0.0;

            double sum = 0.0;

            foreach (double strain in ObjectStrainsList)
                sum += 1.0 / (1.0 + Math.Exp(-(strain / maxStrain * 12.0 - 6.0)));

            return sum;
        }

        protected override double DifficultyValue(List<double> currentStrainPeaks)
            => OsuStrainSkill.DifficultyValue(currentStrainPeaks, SpeedReducedSectionCount, OsuStrainSkill.ReducedStrainBaseline, DecayWeight);

        public static double DifficultyToPerformance(double difficulty) => OsuStrainSkill.DifficultyToPerformance(difficulty);
    }

    internal sealed class FlashlightSkill : StrainSkill
    {
        private const double SkillMultiplier = 0.05512;
        private const double StrainDecayBase = 0.15;

        private double currentStrain;
        private readonly bool hasHiddenMod;
        private readonly FlashlightEvaluator evaluator;

        public FlashlightSkill(bool hasHiddenMod, double radius, double timePreempt, double timeFadeIn)
        {
            double scalingFactor = 52.0 / radius;

            this.hasHiddenMod = hasHiddenMod;
            evaluator = new FlashlightEvaluator(scalingFactor, timePreempt, timeFadeIn);
        }

        protected override double CalculateInitialStrain(double time, OsuDifficultyObject curr, List<OsuDifficultyObject> objects)
        {
            double prevStartTime = curr.Previous(0, objects)?.StartTime ?? 0.0;

            return currentStrain * StrainDecay(time - prevStartTime, StrainDecayBase);
        }

        protected override double StrainValueAt(OsuDifficultyObject curr, List<OsuDifficultyObject> objects)
        {
            currentStrain *= StrainDecay(curr.DeltaTime, StrainDecayBase);
            currentStrain += evaluator.EvaluateDiffOf(curr, objects, hasHiddenMod) * SkillMultiplier;

            return currentStrain;
        }

        protected override double DifficultyValue(List<double> currentStrainPeaks)
        {
            double sum = 0.0;

            foreach (double p in currentStrainPeaks)
                sum += p;

            return sum;
        }

        public static double DifficultyToPerformance(double difficulty) => 25.0 * RustMath.Pow2(difficulty);
    }
}
